### ISSUE TITLE
the extracted key point data 

### ISSUE THREAD

**Issue by chalth** [chenghao-shi/MDGAT-matcher#4]
Hi, can you provide your preprocessed key points data of KITTI which be extracted from USIP?

**Comment by chenghao-shi** [comment]
Actually, we have provided the link to the keypoints data in README, please check this link&nbsp;https://www.ipb.uni-bonn.de/html/projects/MDGAT-matcher/MDGAT-matcher.zip.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenghao-shi/MDGAT-matcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 下午2:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenghao-shi/MDGAT-matcher] the extracted key point data  (Issue #4)





 
Hi, can you provide your preprocessed key points data of KITTI which be extracted from USIP?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
